name: notesapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.5.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/2.png"

  
  flutter_lints: ^6.0.0



flutter:

  uses-material-design: true

  
